const fs=require('fs');
const assert=require('assert');
const app=fs.readFileSync('app.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('styles.css','utf8');
assert(app.includes("const APP_VERSION = '2.0.27'"));
assert(html.includes('id="sidebarToggle"'));
assert(html.includes('class="topbar-brand"'));
assert(html.includes('id="sidebarProfileButton"'));
assert(!html.includes('id="profileShortcut"'));
assert(html.includes('© <span id="footerYear"></span> Profilo 1'));
assert(html.includes('id="aivengersButton"'));
assert(app.includes('Ciao, sono il tuo assistente <strong>AIvengers</strong>. Come posso aiutarti?'));
assert(app.includes("{ id:'stats', label:'Statistiche'"));
assert(app.includes("{ id:'import', label:'Importa ed esporta'"));
assert(app.includes('navigator.geolocation.getCurrentPosition'));
assert(app.includes('serviceChoiceCardsHtml()'));
assert(css.includes('.app-shell.sidebar-collapsed'));
assert(css.includes('--toast-bg'));
assert(css.includes('.app-footer { position:fixed'));
assert(html.includes('id="blockingLoader"'));
assert(app.includes('function showBlockingLoader'));
assert(app.includes('function loaderCopyForRoute'));
assert(app.includes("inlineCinemaLoaderHtml('Ricerca nelle fonti pubbliche'"));
assert(css.includes('.blocking-loader.is-visible'));
assert(css.includes('.suggestion-poster img'));
assert(css.includes('object-fit:cover!important'));
console.log('✓ UI 2.0.21: header, menu, profilo, ricerca, loader e AIvengers verificati');
