const fs=require('fs');
const assert=require('assert');
const app=fs.readFileSync('app.js','utf8');
const css=fs.readFileSync('styles.css','utf8');
const html=fs.readFileSync('index.html','utf8');
assert(app.includes("const APP_VERSION = '2.0.27'"),'Versione 2.0.27 non impostata');
assert(app.includes('function showMetadataIssues('),'Dettaglio titoli metadati mancante');
assert(app.includes('Titoli senza locandina o descrizione'),'Riepilogo metadati incompleti mancante');
assert(app.includes('Copertura effettiva dei metadati'),'Copertura coerente mancante');
assert(app.includes("'last-of-us': {") && app.includes('<svg viewBox="0 0 24 24"'),'Icone SVG tema The Last of Us mancanti');
assert(app.includes('buffy: {') && app.includes('class="theme-detail"'),'Icone SVG tema Buffy mancanti');
assert(css.includes('html[data-theme="last-of-us"] .cinema-loader-art::before'),'Loader The Last of Us mancante');
assert(css.includes('html[data-theme="buffy"] .cinema-loader-art::before'),'Loader Buffy mancante');
assert(css.includes('assets/themes/last-of-us-infected-wall.svg'),'Sfondo The Last of Us mancante');
assert(css.includes('assets/themes/buffy-cemetery.svg'),'Sfondo Buffy mancante');
assert(css.includes('@media (prefers-reduced-motion:reduce)'),'Movimento ridotto non gestito');
assert(css.includes('.metadata-issue-row'),'Stile dettaglio metadati mancante');
assert(html.includes('styles.css?v=2.0.27'),'Cache bust 2.0.27 mancante');
console.log('✓ UI 2.0.27: metadati coerenti e temi show-inspired ridisegnati');
